version: '3'
services:
  dev:
    image: golang:1.19
    command: sleep infinity
    working_dir: ${PWD}
    restart: on-failure
    ports:
      - 8080
    volumes:
      - ${PWD}:${PWD}
      - go-modules:/go/pkg/mod # Put modules cache into a separate volume
volumes:
  go-modules:
