version: "3"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.test
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/conjur-cli-go/output

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: SuperSecret

  conjur:
    image: cyberark/conjur:latest
    command: server -a dev -f /policy/initial_policy.yml
    environment:
      DATABASE_URL: postgres://postgres:SuperSecret@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
      RAILS_ENV: development
    volumes:
      - ./ci/policies:/policy:ro
    depends_on:
      - postgres
    restart: on-failure

  conjur-https:
    image: nginx:alpine
    ports:
      - 443
    volumes:
      - ./ci/https/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ci/https/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./ci/https/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./ci/https/conjur.crt:/cert/tls.crt:ro
      - ./ci/https/conjur.key:/cert/tls.key:ro
      - ./ci/https/ca.crt:/ca/tls.crt:ro
    depends_on:
      - conjur

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
        - "8080"
    depends_on:
      - conjur
    command: ci/test
    volumes:
      - ./output:/conjur-cli-go/output
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:

  conjur-cli:
    image: cyberark/conjur-cli:5
    entrypoint: [ "bash", "-c" ]
    command: [ "sleep 999d" ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
    depends_on:
      - conjur
      - conjur-https


  dev:
    build:
      context: .
      dockerfile: Dockerfile.test
    privileged: true            # to allow debugging
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: sleep infinity
    volumes:
      - .:/conjur-cli-go
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
