version: '3'
services:
  pg:
    image: postgres:10.16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: Bd4+A1QnELGC1Fb5/KauFlVez981OoYblbyfNOCavuQ=

  cli-dev:
    image: golang
    command: bash -c "cd ${PWD}/..; make install; sleep infinity"
    working_dir: ${PWD}/..
    restart: on-failure
    ports:
      - 8080
    volumes:
      - ${PWD}/..:${PWD}/..
      - ./tmp/.conjurrc:/root/.conjurrc
      - ./tmp/.netrc:/root/.netrc
      - ./tmp/.bashrc:/root/.bashrc
      - go-modules:/go/pkg/mod # Put modules cache into a separate volume

volumes:
  go-modules:
