version: '3'
services:
  pg:
    image: postgres:10.16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: Bd4+A1QnELGC1Fb5/KauFlVez981OoYblbyfNOCavuQ=
    volumes:
    # The files add the endpoint /dev to Conjur. This endpoint allows us to carry out typical development tasks such as fetching
    # any role's API key via an unauthenticated HTTP request to Conjur.
      - ./conjur-hacks/dev_initializer.rb:/opt/conjur-server/config/initializers/dev_initializer.rb
      - ./conjur-hacks/dev_controller.rb:/opt/conjur-server/app/controllers/dev_controller.rb

  cli-dev:
    image: golang:1.19
    command: bash -c "cd ${PWD}/..; make install; sleep infinity"
    working_dir: ${PWD}/..
    restart: on-failure
    ports:
      - 8080
    volumes:
      - ${PWD}/..:${PWD}/..
      - ./tmp/.bashrc:/root/.bashrc
      - go-modules:/go/pkg/mod # Put modules cache into a separate volume

volumes:
  go-modules:
