name: ci

on:
  # Run this on pushes to any branch
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run unit tests
        run: bin/test_unit
      - name: Run GoReleaser
        run: bin/build_release --snapshot --skip-validate --rm-dist
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/goreleaser/binaries/*
